language: Android
sudo: false
jdk:
- oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-25.0.0
  - android-25
  - extra-android-support
  - extra
  - sys-img-armeabi-v7a-android-21
  licenses:
  - android-sdk-preview-license-52d11cd2
  - android-sdk-license-.+
  - google-gdk-license-.+
before_script:
- echo n | android create avd -n test -f -t android-21 --abi default/armeabi-v7a
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
  - /usr/local/android-sdk/
notifications:
  slack:
    secure: Swr+cw8BWQeOBitYRjfC9sKRhSD/K5bNX8PoR4r026fwD2LAVRIuQcI/KozYVX3oGONfJioAhyRj1ol6nzsJnaYdhBpMhgf4T6KjaHuNb3oxcAF2RX5i6adSRLJ09Jcs9z0sKM3aCm42OrqMLE7q2U+J8CxnEd8cz4I7jhFf9rtfbWqaeVRMRsikMRPFP2WMBirzmGz76H2avNtppP7HnG0BbdwKf2s9yzWXivUp9FnZ2W/mNeSTOSWH9+K88T1J3XJ+4Vq6kurphV6PTtbL0fNS9m2h5Au0dKgPTRxoR43L//4Z+ifbKs2EvdynWxZIbD5YgKnS1HE3+onYkL4sBdlYelrZwn/58Q5Ke7o7Qar17sUedno7MrgIhMAMSh3lY8XC01ARL7FmlV1UmYWAUsXsHmwFNivrJj7yiTHrnTIaiFr2i/e7j+QYQQ0cD9Y7aRcdGA1eirEarEhvNYy0kaGnou8sg5AVu4p+Ewxl3HZjv1qiAThnOSKvCLIt17DWpUnFQDAdzWlYEgOY0aTfUZA3TpDHoetp9OPU5H2HgoVVKTEGDvM9gFvK3tSsdyKZxsg/tTf3VkrVBY2Tc6j0wcX6Axnu+i2/BF8Y6DzCfvmoCq2VUvkkC4tvBtptR0QzwHlNPtTmkfTebgttcisIwVlI4X70cVXFUVL3pU0ZmA8=
