language: android
jdk: oraclejdk8
android:
  components:
    - build-tools-25.0.0
    - android-25
    - tools
    - tools
    - platform-tools
    - extra-android-m2repository
      # - add-on
      # - extra
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

dependencies:
  pre:
    - android update sdk --no-ui --all --filter build-tools-25.0.0,android-25,extra-android-m2repository
